name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Play-Debug APK
        run: ./gradlew :app:assemblePlayDebug   # <-- playDebug statt debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-play-debug.apk
          path: app/build/outputs/apk/play/debug/app-play-debug.apk
          retention-days: 7
